live_config_reload = true

[window]

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "None"

startup_mode = "SimpleFullscreen"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 16